export default {
  login: "SergeAuck",
  id: 120760582,
  node_id: "U_kgDOBzKpBg",
  avatar_url: "https://avatars.githubusercontent.com/u/120760582?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/SergeAuck",
  html_url: "https://github.com/SergeAuck",
  followers_url: "https://api.github.com/users/SergeAuck/followers",
  following_url:
    "https://api.github.com/users/SergeAuck/following{/other_user}",
  gists_url: "https://api.github.com/users/SergeAuck/gists{/gist_id}",
  starred_url: "https://api.github.com/users/SergeAuck/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/SergeAuck/subscriptions",
  organizations_url: "https://api.github.com/users/SergeAuck/orgs",
  repos_url: "https://api.github.com/users/SergeAuck/repos",
  events_url: "https://api.github.com/users/SergeAuck/events{/privacy}",
  received_events_url: "https://api.github.com/users/SergeAuck/received_events",
  type: "User",
  site_admin: false,
  name: "Serge",
  company: null,
  blog: "",
  location: "Auckland, NZ",
  email: null,
  hireable: null,
  bio: "Developer from NZ",
  twitter_username: null,
  public_repos: 8,
  public_gists: 0,
  followers: 1,
  following: 4,
  created_at: "2022-12-17T00:01:58Z",
  updated_at: "2023-08-12T23:56:06Z",
};
